config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :tweets

  root to: 'tweets#index'

  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'
  get '/auth/signin' => 'sessions#signin'
end

app/models/tweet.rb
require 'twitter'

# Author: Sulaiman Karmali
class Tweet < ActiveRecord::Base
  # Tweet cannot exceed 140 characters
  validates :message, length: { maximum: 140 }

  # When we post a tweet, we set the tweet_id to this special value.
  # When we retrieve a list of all tweets, we update the tweet_id with
  # the Tweet id that Twitter provides.
  TWEET_TEMP_TWEET_ID = 999

  def self.send_tweet_and_save(tweet)
    begin
      self.get_client.update tweet.message.encode
    rescue Exception => e
      logger.debug e.message

      return
    end

    # We are persisting the Tweet that the user created with a special
    # id.  This will help when there are error conditions with sending
    # the tweet.  In future, we could provide for a retry mechanism.
    tweet.tweet_id = TWEET_TEMP_TWEET_ID
    tweet.save
  end

  def self.get_client
    @@client ||= Twitter::REST::Client.new do |config|
      config.consumer_key =         ENV["OMNIAUTH_PROVIDER_KEY"]
      config.consumer_secret =      ENV["OMNIAUTH_PROVIDER_SECRET"]
      config.access_token =         ENV["OMNIAUTH_ACCESS_TOKEN"]
      config.access_token_secret =  ENV["OMNIAUTH_ACCESS_TOKEN_SECRET"]
    end

    @@client
  end

  def self.retrieve_all_tweets
    username = User.first.name unless User.first.nil?
    username ||= ENV['OMNIAUTH_DEFAULT_USERNAME']

    begin
      # TODO - should set a limit on the timeline
      tweets = self.get_client.user_timeline(username)
    rescue Exception => e
      logger.debug e.message

      return nil
    end

    # We now want to persist tweet if it does not exist in database.
    # If it persists, then we need to update the tweet_id to match
    # the tweet id generated by Twitter.
    tweets.each do |tweet|
      twitter_tweet = Tweet.find_by(:tweet_id => tweet.id)
      if (twitter_tweet.nil?)
        # See if there is a db record with invalid tweet_id
        # TODO - this is not the most efficient find_by as tweet message can be quite long
        a_tweet = Tweet.find_by(:message => tweet.full_text, :tweet_id => TWEET_TEMP_TWEET_ID)
        if (a_tweet.nil?)
          a_tweet = Tweet.new(:message => tweet.full_text, :tweet_id => tweet.id)
        else
          # Update the default tweet id with the one Twitter generates.
          a_tweet.update_attributes(:tweet_id => tweet.id)
        end

        a_tweet.save
      end
    end

    tweets
  end
end

app/models/user.rb
# Author: Sulaiman Karmali
class User < ActiveRecord::Base

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth['provider']
      user.uid = auth['uid']
      if auth['info']
         user.name = auth['info']['name'] || ""
      end
    end
  end

end

app/controllers/application_controller.rb
# Author: Sulaiman Karmali
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user
  helper_method :user_signed_in?
  helper_method :correct_user?

  private
    def current_user
      begin
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
      rescue Exception => e
        nil
      end
    end

    def user_signed_in?
      return true if current_user
    end

    def correct_user?
      @user = User.find(params[:id])
      unless current_user == @user
        redirect_to root_url, :alert => "Access denied."
      end
    end

    def authenticate_user!
      if !current_user
        redirect_to root_url, :alert => 'You need to sign in for access to this page.'
      end
    end

end

app/controllers/sessions_controller.rb
# Author: Sulaiman Karmali
class SessionsController < ApplicationController

  def new
    redirect_to '/auth/twitter'
  end

  def create
    auth = request.env["omniauth.auth"]
    user = User.where(:provider => auth['provider'],
                      :uid => auth['uid'].to_s).first || User.create_with_omniauth(auth)
    reset_session
    session[:user_id] = user.id
    redirect_to root_url, :notice => 'Signed in!'
  end

  def signin
  end

  def destroy
    reset_session
    redirect_to '/auth/signin', :notice => 'Signed out!'
  end

  def failure
    redirect_to root_url, :alert => "Authentication error: #{params[:message].humanize}"
  end

end

app/controllers/tweets_controller.rb
# Author: Sulaiman Karmali
class TweetsController < ApplicationController
  before_action :set_tweets, only: [:index]
  before_action :set_twitter_tweets, only: [:index, :create]

  def index
    respond_to do |format|
      format.html
    end
  end

  def create
    @tweet = Tweet.create(:message => params[:message])

    respond_to do |format|
      if Tweet.send_tweet_and_save @tweet
        flash[:notice] = "Message tweeted at #{Time.now}"
        format.html { redirect_to tweets_path }
      else
        flash[:notice] = "Message failed to save."
        format.html { redirect_to tweets_path }
      end
    end
  end

  private

  def set_tweets
    @tweets = Tweet.all
  end

  def set_twitter_tweets
    @twitter_tweets = Tweet.retrieve_all_tweets
    @twitter_tweets = [] if @twitter_tweets.nil?
  end
end

app/controllers/users_controller.rb
# Author: Sulaiman Karmali
class UsersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :correct_user?, :except => [:index]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Sign out', signout_path %></li>
<% else %>
  <li><%= link_to 'Sign in', signin_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Tweets', tweets_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Sulaiman's Tweet App" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Sulaiman's Tweet App" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/tweets/_tweet_form.html.erb
<div class="tweet_form">
    <%= form_tag do %>
      <%= label_tag :question, 'Enter Tweet' %> <br />
      <%= text_area_tag :message, nil, size: "64x10" %> <br />
      <%= submit_tag "Tweet!"%>
    <% end %>
</div>

app/views/tweets/_twitter_tweets.erb
<div id="twitter_tweets">
    <br><br><br>
    <h1>Tweets from Twitter</h1>

    <table class="table table-striped table-bordered table-condensed">
        <thead>
          <th>Timestamp</th>
          <th>Message</th>
          <th>Tweet Link</th>
        </thead>
        <tbody>
          <% @twitter_tweets.each do |tweet| %>
            <tr>
              <td><%= tweet.created_at %></td>
              <td><%= tweet.full_text %></td>
              <td><%= link_to "#{tweet.id}", "https://twitter.com/skarmali/status/#{tweet.id}" %></td>
            </tr>
          <% end %>
        </tbody>
    </table>
</div>

app/views/tweets/index.html.erb
<% if user_signed_in? %>
  <div class="tweets">
    <h1>Send a Tweet:</h1>

    <%= render partial: "tweet_form" %>
    <%= render partial: "twitter_tweets" %>
  </div>
<% end %>

app/views/users/_user.html.erb
<td><%= link_to user.name, user %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>